//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIT.Tools.VisualStudioTextTransform.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VisualStudioActivityLog.xml")]
        public string VisualStudioLogfile {
            get {
                return ((string)(this["VisualStudioLogfile"]));
            }
            set {
                this["VisualStudioLogfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SelfHostVisualStudio {
            get {
                return ((bool)(this["SelfHostVisualStudio"]));
            }
            set {
                this["SelfHostVisualStudio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\yangjiefeng\\Documents\\GitHub\\dddml-dotnet-tools\\Dddml.T4.ProjectTools\\bi" +
            "n\\Debug\\Dddml.T4.ProjectTools.exe")]
        public string ProjectToolsFileName {
            get {
                return ((string)(this["ProjectToolsFileName"]));
            }
            set {
                this["ProjectToolsFileName"] = value;
            }
        }
    }
}
